petitions/urls.py
from django.urls import path

from . import views

app_name = 'petitions'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:petition_id>/', views.display, name='display'),
    path('<int:petition_id>/embed', views.embed, name='embed'),
    path('<int:petition_id>/signatures', views.signatures, name='signatures'),
    path('<int:petition_id>/signatures.csv',
         views.signatures_csv,
         name='signatures_csv'),
    path('confirm/<str:secret>', views.confirm_signature, name='confirm'),
    path('thanks', views.thanks, name='thanks'),
]

platpet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('petitions/', include('petitions.urls')),
    path('admin/', admin.site.urls),
]

petitions/models.py
from django.db import models


class Petition(models.Model):
    name = models.CharField(max_length=400)
    description = models.TextField()
    requires_confirmation = models.BooleanField(default=True)
    consent_text = models.TextField(default="", blank=True)

    def __str__(self):
        return "%i: %s" % (self.id, self.name)


class Signature(models.Model):
    petition = models.ForeignKey(Petition, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)
    city = models.CharField(max_length=150)
    email = models.EmailField()
    contact_consent = models.BooleanField(default=False, db_index=True)
    is_confirmed = models.BooleanField(default=True, db_index=True)
    confirmation_secret = models.CharField(max_length=400, null=True)

    class Meta:
        unique_together = ["petition_id", "email"]

petitions/forms.py
from django.forms import ModelForm, HiddenInput, CheckboxInput
from django.utils.translation import gettext as _
from django.utils.safestring import mark_safe

from .models import Signature


consent_label = mark_safe(_('I consent to my email address being stored and used to send further information on the activities of the Platform Možemo! More information is available in the <a href="https://www.mozemo.hr/privacy-policy/">Privacy Policy</a>.'))


class SignatureForm(ModelForm):
    class Meta:
        model = Signature
        fields = ['petition', 'name', 'city', 'email', 'contact_consent']
        widgets = {
            'petition': HiddenInput(),
        }
        labels = {
            "name": _("Name"),
            "city": _("City"),
            "email": _("Email Address"),
            "contact_consent": consent_label
        }

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)

        if 'petition' in self.initial \
           and self.initial['petition'].consent_text != "":
            consent_text = mark_safe(self.initial['petition'].consent_text)
        else:
            consent_text = consent_label

        self.fields['contact_consent'].label = consent_text

petitions/views.py
import csv
import os

from django.http import \
    HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core import signing
from django.contrib import messages
from django.utils.translation import gettext as _
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt

from .models import Petition, Signature
from .forms import SignatureForm
from .email import send_verification_email


def index(request):
    petitions = Petition.objects.order_by("-id")
    return HttpResponse(petitions)


@csrf_exempt
@xframe_options_exempt
def display(request, petition_id):
    petition = get_object_or_404(Petition, pk=petition_id)
    message = ""

    if request.method == "POST":
        signature_form = SignatureForm(request.POST)

        if signature_form.is_valid():
            if signature_form.cleaned_data["petition"].id != petition_id:
                raise Exception("Nope.")

            new_signature = signature_form.save(commit=False)

            if petition.requires_confirmation:
                new_signature.is_confirmed = False
                secret = send_verification_email(
                    os.getenv("PLATPET_HOSTNAME",
                              "https://peticije.sudjeluj.org"),
                    petition,
                    new_signature.email
                )
                new_signature.confirmation_secret = secret
                message = _("Petition successfully signed. Please check "
                            + "your inbox for the link to confirm your "
                            + "signature.")
            else:
                message = _("Petition successfully signed. Thanks!")

            new_signature.save()

            signature_form = SignatureForm(initial={"petition": petition})
    else:
        signature_form = SignatureForm(initial={"petition": petition})

    context = {
        "petition": petition,
        "signature_form": signature_form,
        "message": message,
    }
    return HttpResponse(render(request, 'petitions/display.html', context))


def embed(request, petition_id):
    # assume only petition administrators will be authenticated...
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    context = {
        "petition_id": petition_id
    }

    return render(request,
                  'petitions/embed.html',
                  context,
                  content_type="text/plain")


def signatures(request, petition_id):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    petition = get_object_or_404(Petition, pk=petition_id)
    signatures = Signature.objects.filter(petition_id=petition_id,
                                          is_confirmed=True)

    context = {
        "petition": petition,
        "signatures": signatures,
    }
    return HttpResponse(render(request, 'petitions/signatures.html', context))


def signatures_csv(request, petition_id):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    signatures = Signature.objects.filter(petition_id=petition_id,
                                          is_confirmed=True)

    response = HttpResponse(content_type='text/csv')

    writer = csv.writer(response)
    for signature in signatures:
        writer.writerow([
            signature.name,
            signature.city,
            signature.email,
            signature.contact_consent
        ])

    return response


def confirm_signature(request, secret):
    verification_object = signing.loads(secret)
    petition = get_object_or_404(Petition,
                                 pk=verification_object["petition_id"])
    signature = Signature.objects.get(petition_id=petition.id,
                                      email=verification_object["email"])

    signature.is_confirmed = True
    signature.save()
    return HttpResponseRedirect(reverse('petitions:thanks'))


def thanks(request):
    return HttpResponse(_("Thanks for confirming"))

petitions/templates/petitions/base.html
{% extends 'petitions/bootstrap.html' %}

{% load bootstrap4 %}

{% block bootstrap4_content %}
<div class="container" style="padding-top: 20px;">
    {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

petitions/templates/petitions/bootstrap.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% if 'use_i18n'|bootstrap_setting %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Page title -->
        <title>{% block title %}Platpet{% endblock %}</title>

        <!-- Bootstrap CSS -->
        {% bootstrap_css %}

        {% block bootstrap4_extra_head %}{% endblock %}

    </head>

    <body>
        {% block bootstrap4_before_content %}{% endblock %}
        {% block bootstrap4_content %}{% endblock %}
        {% block bootstrap4_after_content %}{% endblock %}

    </body>

</html>

petitions/templates/petitions/display.html
{% extends 'petitions/base.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
{% if message %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
</div>
{% endif %}

<h1>{{ petition.name }}</h1>

<p>
    {{ petition.description }}
</p>

<h2>{% trans "Sign" %}</h2>

<form action="." method="post">
    {% csrf_token %}
    {% bootstrap_form signature_form %}

    <input type="submit" value="{% trans "Submit" %}">
</form>

{% if request.user.is_superuser %}
<p style="margin-top:20px;">
    <a href="{% url 'petitions:signatures' petition.id %}">Vidi potpise</a> |
    <a target="_blank" href="{% url 'petitions:embed' petition.id %}">Embed kod</a>
</p>
{% endif %}

<script>
 window.onload = function() {
     const height = document.body.scrollHeight;

     if (window.parent) {
         window.parent.postMessage(`${height}px`, "*");
     }
 };
</script>
{% endblock %}

petitions/templates/petitions/email-inlined.html
{% load i18n %}

<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{% trans "Please confirm signature" %}</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      #MessageViewBody a {
        color: inherit;
        text-decoration: none;
        font-size: inherit;
        font-family: inherit;
        font-weight: inherit;
        line-height: inherit;
      }
      .btn-primary table td:hover {
        background-color: #34495e !important;
      }
      .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">{% trans "Please confirm your petition signature by clicking on a link." %}</span>
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">
                            {% trans "Please confirm your signature for the petition" %} <strong>{{ petition.name }}</strong>.
                        </p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">
                            {% trans "To do so, please click on the following link" %}:
                        </p>
                        <table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;">
                          <tbody>
                            <tr>
                              <td align="left" style="font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;">
                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;">
                                  <tbody>
                                    <tr>
                                        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top; background-color: #3498db; border-radius: 5px; text-align: center;"> <a href="{{ url_root }}{% url 'petitions:confirm' secret %}" target="_blank" style="display: inline-block; color: #ffffff; background-color: #3498db; border: solid 1px #3498db; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; border-color: #3498db;">{% trans "Confirm signature" %}</a> </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">{% trans "Thank you!" %}</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>

            <!-- START FOOTER
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
              <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                <tr>
                  <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    <span class="apple-link" style="color: #999999; font-size: 12px; text-align: center;">Company Inc, 3 Abbey Road, San Francisco CA 94102</span>
                    <br> Don't like these emails? <a href="http://i.imgur.com/CScmqnj.gif" style="text-decoration: underline; color: #999999; font-size: 12px; text-align: center;">Unsubscribe</a>.
                  </td>
                </tr>
                <tr>
                  <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    Powered by <a href="http://htmlemail.io" style="color: #999999; font-size: 12px; text-align: center; text-decoration: none;">HTMLemail</a>.
                  </td>
                </tr>
              </table>
            </div>
            END FOOTER -->

          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

petitions/templates/petitions/embed.html
<iframe id="peticija" src="https://peticije.sudjeluj.org/petitions/{{ petition_id }}/" width="100%" height="500" frameborder="0"></iframe>
<script>
 window.addEventListener("message", (event) => {
     if (event.data != "") {
         document.getElementById("peticija").height = event.data;
     }
 });
</script>

petitions/templates/petitions/signatures.html
{% extends 'petitions/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>{{ petition.name }} - Signatures</h1>

<p>
    <a href="{% url 'petitions:signatures_csv' petition.id %}">Export as CSV</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Nr.</th>
            <th>Name</th>
            <th>City</th>
            <th>Email</th>
            <th>Consent</th>
        </tr>
    </thead>

    <tbody>
        {% for signature in signatures %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ signature.name }}</td>
            <td>{{ signature.city }}</td>
            <td>{{ signature.email }}</td>
            <td>{{ signature.contact_consent }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<p>
    <a href="{% url 'petitions:signatures_csv' petition.id %}">Export as CSV</a>
</p>
{% endblock %}